# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2cf8e286e3501e03220eebf9563333f9"
application_url = "https://tax-airline-losing-saddam.trycloudflare.com/shopify/order-printer"
embedded = true
name = "Order Printer Demo"
handle = "pdf_test"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[auth]
redirect_urls = [
  "https://tax-airline-losing-saddam.trycloudflare.com/shopify/order-printer/auth"
]

[app_proxy]
url = "https://tax-airline-losing-saddam.trycloudflare.com"
subpath = "order-printer"
prefix = "apps"

[pos]
embedded = false
