# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87e74578b5674b3f8a3f100fdc640e93"
application_url = "https://staging-apps.pullush.com/shopify/order-printer"
embedded = true
name = "Order Printer Demo"
handle = "order_printer_handle"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[auth]
redirect_urls = [
  "https://staging-apps.pullush.com/shopify/order-printer/auth"
]

[app_proxy]
url = "https://staging-apps.pullush.com"
subpath = "order-printer"
prefix = "apps"

[pos]
embedded = false
