# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b532f4655dbba6b411aa1b704520ed69"
application_url = "https://funeral-shipped-state-arrived.trycloudflare.com/shopify/pdf"
embedded = true
name = "PDF_APP_v2"
handle = "pdf_app_v2"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[auth]
redirect_urls = [ "https://funeral-shipped-state-arrived.trycloudflare.com/shopify/pdf/auth" ]

[pos]
embedded = false

[app_proxy]
url = "https://funeral-shipped-state-arrived.trycloudflare.com"
subpath = "order-printer"
prefix = "apps"
